"use client";
import { useState } from "react"; import { useRouter } from "next/navigation"; import { Ban, Loader2, Plus, Warehouse } from "lucide-react"; import { toast } from "sonner"; import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import type { InventoryUnit } from "@/types/database"; import { StatusBadge } from "@/components/common/status-badge";
export function InventoryManager({productId,units}:{productId:string;units:InventoryUnit[]}){const router=useRouter();const[codes,setCodes]=useState("");const[prefix,setPrefix]=useState("D-");const[start,setStart]=useState(1);const[end,setEnd]=useState(8);const[saving,setSaving]=useState(false);const counts={available:units.filter((u)=>u.status==="AVAILABLE").length,blocked:units.filter((u)=>u.status==="BLOCKED").length,inactive:units.filter((u)=>u.status==="INACTIVE").length};
 const generate=()=>{if(end<start||end-start>99){toast.error("Choose a range of up to 100 desks.");return;}const width=Math.max(2,String(end).length);setCodes(Array.from({length:end-start+1},(_,index)=>`${prefix}${String(start+index).padStart(width,"0")}`).join(", "));};
 const add=async()=>{const list=codes.split(/[\s,]+/).map((v)=>v.trim().toUpperCase()).filter(Boolean);if(!list.length)return;setSaving(true);const response=await fetch(`/api/operator/products/${productId}/inventory`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({codes:list})});const result=await response.json();if(!response.ok)toast.error(result.error?.message??"Desks could not be added.");else{toast.success(`${list.length} desk units added`);setCodes("");router.refresh();}setSaving(false);};
 const update=async(unit:InventoryUnit,patch:Record<string,unknown>)=>{const response=await fetch(`/api/operator/products/${productId}/inventory/${unit.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(patch)});const result=await response.json();if(!response.ok)toast.error(result.error?.message??"Desk could not be updated.");else{toast.success("Desk updated");router.refresh();}};
 const deactivate=async(unit:InventoryUnit)=>{const response=await fetch(`/api/operator/products/${productId}/inventory/${unit.id}`,{method:"DELETE"});if(response.ok){toast.success("Desk deactivated");router.refresh();}else toast.error("Desk could not be deactivated.");};
 return <section className="surface-card mt-6 p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><p className="eyebrow">Dedicated desk inventory</p><h2 className="mt-2 text-xl font-semibold">Individual desk units</h2><p className="mt-1 text-sm text-muted-foreground">Create, block, and schedule the desks customers can reserve.</p></div><div className="flex flex-wrap gap-2">{[["Total",units.length],["Available",counts.available],["Blocked",counts.blocked],["Inactive",counts.inactive]].map(([label,value])=><span key={String(label)} className="rounded-full border bg-card px-3 py-1.5 text-xs"><strong>{value}</strong> {label}</span>)}</div></div>
 <div className="mt-6 rounded-xl border bg-muted/20 p-4"><p className="text-sm font-medium">Generate desk codes</p><div className="mt-3 grid gap-3 sm:grid-cols-4"><Input value={prefix} onChange={(e)=>setPrefix(e.target.value.toUpperCase())} aria-label="Desk prefix" placeholder="Prefix"/><Input type="number" value={start} onChange={(e)=>setStart(Number(e.target.value))} aria-label="Start number"/><Input type="number" value={end} onChange={(e)=>setEnd(Number(e.target.value))} aria-label="End number"/><Button type="button" variant="outline" onClick={generate}><Warehouse/>Generate</Button></div><div className="mt-3 flex flex-col gap-2 sm:flex-row"><Input value={codes} onChange={(e)=>setCodes(e.target.value)} placeholder="D-01, D-02, D-03" aria-label="Desk codes"/><Button type="button" onClick={add} disabled={saving||!codes.trim()}>{saving?<Loader2 className="animate-spin"/>:<Plus/>}Add desks</Button></div></div>
 {units.length===0?<div className="mt-5 rounded-xl border border-dashed p-8 text-center"><Warehouse className="mx-auto text-muted-foreground"/><p className="mt-3 text-sm font-medium">No desk units yet</p><p className="mt-1 text-xs text-muted-foreground">Generate a range or enter individual codes above.</p></div>:<div className="mt-5 overflow-x-auto rounded-xl border"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-muted/50 text-xs text-muted-foreground"><tr><th className="p-3 font-medium">Code</th><th className="p-3 font-medium">Name</th><th className="p-3 font-medium">Status</th><th className="p-3 font-medium">Available from</th><th className="p-3 font-medium text-right">Action</th></tr></thead><tbody className="divide-y">{units.map((unit)=><tr key={unit.id}><td className="p-3 font-mono font-semibold">{unit.code}</td><td className="p-3"><Input defaultValue={unit.name??""} placeholder="Optional desk name" onBlur={(e)=>{if(e.target.value!==(unit.name??""))update(unit,{name:e.target.value||null})}}/></td><td className="p-3"><select value={unit.status} onChange={(e)=>update(unit,{status:e.target.value})} className="h-8 rounded-lg border bg-background px-2"><option value="AVAILABLE">Available</option><option value="BLOCKED">Blocked</option><option value="INACTIVE">Inactive</option></select></td><td className="p-3"><Input type="date" defaultValue={unit.available_from??""} onBlur={(e)=>update(unit,{availableFrom:e.target.value||null})}/></td><td className="p-3 text-right">{unit.status!=="INACTIVE"?<Button type="button" variant="destructive" size="sm" onClick={()=>deactivate(unit)}><Ban/>Deactivate</Button>:<StatusBadge status="INACTIVE"/>}</td></tr>)}</tbody></table></div>}
 </section>}
