"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Clock3, Loader2, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { currency } from "@/lib/products/labels";
import type { BookingHold } from "@/types/database";
export function CheckoutPanel({ hold }: { hold: BookingHold }) {
  const router = useRouter(); const [seconds, setSeconds] = useState<number|null>(null); const [processing,setProcessing]=useState<"SUCCESS"|"FAILED"|null>(null); const [error,setError]=useState("");
  useEffect(()=>{const tick=()=>setSeconds(Math.max(0,Math.floor((new Date(hold.expires_at).getTime()-Date.now())/1000)));tick();const timer=window.setInterval(tick,1000);return()=>window.clearInterval(timer)},[hold.expires_at]);
  const pay=async(outcome:"SUCCESS"|"FAILED")=>{setProcessing(outcome);setError("");const response=await fetch("/api/customer/payments/simulate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({holdId:hold.id,outcome})});const result=await response.json();if(!response.ok){setError(result.error?.message??"Payment simulation failed.");setProcessing(null);return}if(outcome==="FAILED"){setError("The simulated payment failed and your hold was released. No charge was made.");setProcessing(null);return}router.push(`/booking-confirmation/${result.data.booking.id}`);router.refresh()};
  const snapshot=hold.pricing_snapshot; const expired=seconds===0||hold.status!=="ACTIVE"; const clock=seconds===null?"--:--":`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
  return <div className="grid gap-6 lg:grid-cols-[1fr_380px]"><section className="surface-card p-6"><p className="eyebrow">Review reservation</p><h1 className="mt-3 text-3xl font-semibold">{String(snapshot.productName??"Workspace booking")}</h1><dl className="mt-7 grid gap-4 rounded-2xl bg-slate-50 p-5 sm:grid-cols-2"><Item label="Workspace type" value={String(snapshot.productType??hold.product_type).replaceAll("_"," ")} /><Item label="Date" value={String(snapshot.bookingDate??snapshot.startDate??"—")} /><Item label="Time / end date" value={String(snapshot.startTime ? `${snapshot.startTime}–${snapshot.endTime}` : snapshot.endDate??"—")} /><Item label="Quantity" value={String(snapshot.months ? `${snapshot.months} month(s)` : hold.quantity)} /></dl><div className="mt-6 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm leading-6 text-blue-900"><ShieldCheck className="mb-2 size-5" /><strong>Simulated payment</strong><br/>This demo creates no real charge. Pricing and confirmation are still processed through the secure booking workflow.</div></section><aside className="surface-card h-fit p-6"><div className={`flex items-center justify-between rounded-xl p-3 ${seconds!==null&&seconds<120?"bg-amber-50 text-amber-800":"bg-slate-100"}`}><span className="flex items-center gap-2 text-sm font-medium"><Clock3 className="size-4" />Hold expires in</span><span className="font-mono font-semibold">{clock}</span></div><div className="mt-5 space-y-3 text-sm"><Price label="Subtotal" value={hold.subtotal}/><Price label="Demo tax (18%)" value={hold.tax_amount}/>{hold.security_deposit>0&&<Price label="Security deposit" value={hold.security_deposit}/>}<div className="flex justify-between border-t pt-4 text-base font-semibold"><span>Total</span><span>{currency(hold.total_amount)}</span></div></div>{error&&<p role="alert" className="mt-4 rounded-xl bg-destructive/5 p-3 text-sm text-destructive">{error}</p>}<Button className="mt-6 h-11 w-full" disabled={seconds===null||expired||Boolean(processing)} onClick={()=>pay("SUCCESS")}>{processing==="SUCCESS"&&<Loader2 className="animate-spin"/>}{expired?"Hold expired":processing==="SUCCESS"?"Processing…":"Simulate successful payment"}</Button><Button variant="outline" className="mt-2 w-full" disabled={seconds===null||expired||Boolean(processing)} onClick={()=>pay("FAILED")}>Simulate failed payment</Button><p className="mt-3 text-center text-xs text-muted-foreground">No real payment credentials are collected.</p></aside></div>;
}
function Item({label,value}:{label:string;value:string}){return <div><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 text-sm font-medium capitalize">{value}</dd></div>}
function Price({label,value}:{label:string;value:number}){return <div className="flex justify-between"><span className="text-muted-foreground">{label}</span><span>{currency(value)}</span></div>}
