import Link from "next/link";
import { ArrowRight, Building2, CalendarDays, DoorOpen, Search, Users } from "lucide-react";
import { MarketplaceHeader } from "@/components/marketplace/marketplace-header";
import { LocationCard } from "@/components/marketplace/location-card";
import { buttonVariants } from "@/components/ui/button";
import { getMarketplaceLocations } from "@/lib/data/phase3";
const categories = [{ label: "Day passes", value: "DAY_PASS", icon: CalendarDays }, { label: "Meeting rooms", value: "MEETING_ROOM", icon: Users }, { label: "Dedicated desks", value: "DEDICATED_DESK", icon: Building2 }, { label: "Private cabins", value: "PRIVATE_CABIN", icon: DoorOpen }];
export const metadata = { title: "OperatorOS | Workspaces, ready when you are", description: "Discover and book verified coworking spaces." };
export default async function Home() {
  const locations = await getMarketplaceLocations().catch(() => []);
  return <main className="min-h-screen bg-slate-50/60"><MarketplaceHeader /><section className="relative overflow-hidden bg-slate-950 text-white"><div className="absolute inset-0 opacity-70 [background-image:radial-gradient(circle_at_15%_20%,#2563eb_0,transparent_27%),radial-gradient(circle_at_90%_80%,#0f766e_0,transparent_25%)]" /><div className="relative mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28"><p className="text-xs font-semibold tracking-[.2em] text-blue-300 uppercase">Verified flexible workspaces</p><h1 className="mt-5 max-w-4xl text-4xl font-semibold leading-[1.05] tracking-[-.045em] sm:text-6xl lg:text-7xl">A better workspace is closer than you think.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Search trusted coworking locations, see real availability, and reserve the way you want to work.</p><form action="/locations" className="mt-9 flex max-w-2xl gap-2 rounded-2xl bg-white p-2 shadow-2xl"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-5 -translate-y-1/2 text-slate-400" /><input name="city" aria-label="Search by city" placeholder="Search Gurugram, Bengaluru…" className="h-12 w-full rounded-xl pl-11 pr-3 text-slate-950 outline-none" /></div><button className={buttonVariants({ size: "lg" })}>Search spaces<ArrowRight /></button></form><div className="mt-8 grid max-w-3xl grid-cols-2 gap-2 sm:grid-cols-4">{categories.map(({ label, value, icon: Icon }) => <Link key={value} href={`/locations?category=${value}`} className="rounded-xl border border-white/10 bg-white/[.07] p-4 text-sm font-medium backdrop-blur transition hover:bg-white/[.13]"><Icon className="mb-4 size-5 text-blue-300" />{label}</Link>)}</div></div></section><section className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><div className="flex items-end justify-between gap-6"><div><p className="eyebrow">Featured locations</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Find your next place to work</h2></div><Link href="/locations" className={buttonVariants({ variant: "outline" })}>Explore all<ArrowRight /></Link></div>{locations.length ? <div className="mt-8 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{locations.slice(0, 6).map((workspace) => <LocationCard key={workspace.location.id} workspace={workspace} />)}</div> : <div className="mt-8 rounded-3xl border border-dashed bg-white p-12 text-center"><Building2 className="mx-auto size-9 text-muted-foreground" /><h3 className="mt-4 font-semibold">Marketplace listings are being prepared</h3><p className="mt-2 text-sm text-muted-foreground">Approved, published locations will appear here automatically.</p></div>}</section><footer className="border-t bg-white px-5 py-8 text-center text-sm text-muted-foreground">OperatorOS · Verified workspaces and secure booking holds</footer></main>;
}
